#ifndef ZL_HEATING_STAGE_CODE_GENERATE_ALL_PIN
#define ZL_HEATING_STAGE_CODE_GENERATE_ALL_PIN

#define ZLHS_CS1238_SCK_PIN 2
#define ZLHS_CS1238_DATA_PIN 1
#define ZLHS_HEATER_PIN 18
#define ZLHS_BUZZER_PIN 48
#define ZLHS_FAN_PIN 17

#define ZLHS_SPI0_CS0_PIN 10
#define ZLHS_SPI0_SCK_PIN 12
#define ZLHS_SPI0_MOSI_PIN 11
#define ZLHS_SPI0_MISO_PIN 13

#define ZLHS_SPI1_CS0_PIN 4
#define ZLHS_SPI1_CS1_PIN 38
#define ZLHS_SPI1_SCK_PIN 6
#define ZLHS_SPI1_MOSI_PIN 5
#define ZLHS_SPI1_MISO_PIN 7

#define ZLHS_I2C_SCL_PIN 15
#define ZLHS_I2C_SDA_PIN 16

#define ZLHS_USB_DP_PIN 20
#define ZLHS_USB_DN_PIN 19

#define ZLHS_TFT_BL_PIN 21
#define ZLHS_TFT_DC_PIN 14
#define ZLHS_TFT_RST_PIN 47
#define ZLHS_TFT_CS0_PIN ZLHS_SPI0_CS0_PIN
#define ZLHS_TFT_SCK_PIN ZLHS_SPI0_SCK_PIN
#define ZLHS_TFT_MOSI_PIN ZLHS_SPI0_MOSI_PIN
#define ZLHS_TFT_MISO_PIN ZLHS_SPI0_MISO_PIN

#define ZLHS_TFT_TOUCH_INT_PIN 9
#define ZLHS_TFT_TOUCH_CS0_PIN ZLHS_SPI1_CS0_PIN
#define ZLHS_TFT_TOUCH_SCK_PIN ZLHS_SPI1_SCK_PIN
#define ZLHS_TFT_TOUCH_MOSI_PIN ZLHS_SPI1_MISO_PIN
#define ZLHS_TFT_TOUCH_MISO_PIN ZLHS_SPI1_MOSI_PIN

#define ZLHS_SD_CS0_PIN ZLHS_SPI1_CS1_PIN
#define ZLHS_SD_SCK_PIN ZLHS_SPI1_SCK_PIN
#define ZLHS_SD_MOSI_PIN ZLHS_SPI1_MOSI_PIN
#define ZLHS_SD_MISO_PIN ZLHS_SPI1_MISO_PIN

#define ZLHS_EC11_DT_PIN 42
#define ZLHS_EC11_SCK_PIN 41
#define ZLHS_EC11_SW_PIN 40

#endif